# Generated by Django 2.2.2 on 2019-07-07 10:10

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon_url', models.URLField(default='http://localhost:8000/static/unit_icons/axe.png')),
                ('tile_url', models.URLField(default='http://localhost:8000/static/unit_icons/axe.png')),
                ('tier', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Value must be between 1 and 5'), django.core.validators.MaxValueValidator(5, 'Value must be between 1 and 5')])),
            ],
        ),
        migrations.CreateModel(
            name='UnitLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value must be non-negative'), django.core.validators.MaxValueValidator(31, 'Value must be below 32')])),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='undertiers.Map')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='undertiers.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='pieces',
            field=models.ManyToManyField(through='undertiers.UnitLoc', to='undertiers.Unit'),
        ),
        migrations.AddField(
            model_name='map',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('min_units', models.IntegerField()),
                ('max_units', models.IntegerField()),
                ('icon_url', models.URLField(default='http://localhost:8000/static/alliance_icons/brawny.png')),
                ('description', models.CharField(default='', max_length=200)),
                ('synergies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, null=True, size=None)),
                ('units', models.ManyToManyField(to='undertiers.Unit')),
            ],
        ),
    ]
