# Generated by Django 2.2.2 on 2019-06-25 08:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alliances', models.CharField(max_length=200, validators=[django.core.validators.int_list_validator])),
                ('icon_url', models.URLField()),
                ('tile_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='undertiers.Map')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='undertiers.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='pieces',
            field=models.ManyToManyField(through='undertiers.Units', to='undertiers.Unit'),
        ),
        migrations.AddField(
            model_name='map',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
