# Generated by Django 2.2.2 on 2019-07-08 09:12

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('undertiers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alliance',
            name='description',
        ),
        migrations.AlterField(
            model_name='alliance',
            name='synergies',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, null=True, size=None),
        ),
    ]
