# Generated by Django 2.2.2 on 2019-06-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undertiers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Units',
            new_name='UnitLoc',
        ),
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('min_units', models.IntegerField()),
                ('max_units', models.IntegerField()),
                ('icon_url', models.URLField()),
                ('units', models.ManyToManyField(to='undertiers.Unit')),
            ],
        ),
    ]
