# Generated by Django 2.2.2 on 2019-06-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undertiers', '0002_auto_20190625_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='alliances',
        ),
    ]
