# Generated by Django 2.2.2 on 2019-07-16 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undertiers', '0002_auto_20190708_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitloc',
            name='pos',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value must be non-negative'), django.core.validators.MaxValueValidator(8, 'Value must be below 32')]),
        ),
    ]
