# Generated by Django 2.2.2 on 2019-06-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undertiers', '0003_remove_unit_alliances'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliance',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='map',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
