# Generated by Django 2.2.2 on 2019-07-16 09:04

import django.core.validators
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('undertiers', '0003_auto_20190716_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitloc',
            name='posx',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value must be non-negative'), django.core.validators.MaxValueValidator(8, 'Value must be below 32')]), default=[0, 0], size=None),
            preserve_default=False,
        ),
    ]
