# Generated by Django 2.2.2 on 2019-07-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undertiers', '0004_unitloc_posx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitloc',
            name='pos',
        ),
    ]
