# Generated by Django 2.2.2 on 2019-07-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undertiers', '0005_remove_unitloc_pos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitloc',
            old_name='posx',
            new_name='pos',
        ),
    ]
