# Generated by Django 2.2.2 on 2019-06-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undertiers', '0005_auto_20190629_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliance',
            name='icon_url',
            field=models.URLField(default='http://localhost:8000/static/alliance_icons/brawny.png'),
        ),
    ]
