# Generated by Django 2.2.2 on 2019-07-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undertiers', '0006_auto_20190629_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliance',
            name='synergy_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='alliance',
            name='synergy_2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='alliance',
            name='synergy_3',
            field=models.CharField(default='', max_length=200),
        ),
    ]
