# Generated by Django 2.2.2 on 2019-08-06 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('undertiers', '0010_auto_20190722_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='upvote',
            field=models.ManyToManyField(related_name='upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
