# Generated by Django 2.2.2 on 2019-08-06 21:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('undertiers', '0012_auto_20190806_1208'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together={('user', 'map')},
        ),
    ]
