# Generated by Django 2.2.2 on 2019-08-07 19:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('undertiers', '0013_auto_20190806_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upvote',
            old_name='map',
            new_name='board',
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together={('user', 'board')},
        ),
    ]
