# Generated by Django 2.2.2 on 2019-09-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undertiers', '0019_auto_20190811_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='early_game',
            field=models.ManyToManyField(related_name='EarlyGame', to='undertiers.Unit'),
        ),
        migrations.AddField(
            model_name='map',
            name='mid_game',
            field=models.ManyToManyField(related_name='MidGame', to='undertiers.Unit'),
        ),
    ]
