# Generated by Django 2.2.2 on 2019-10-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undertiers', '0021_auto_20190922_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
